print('       TIP CALCULADOR       ')
print('----------------------------')
bill = float(input("What was the total of the bill? --> $"))
tip = int(input("How much tip would you like to give? 10%, 12%, or 15%? --> "))
people = int(input('How many people to split the bill? --> '))
print('----------------------------')
total = bill * (1 + tip/100) 
print(f'The total paid is: ${round(total,2)}')
print(f'Each person should pay: ${round(total/people,2)}')